// File generated from "node scripts/generateContent.js", DO NOT EDIT/COMMIT
export default {
  vue3: () => import("./vue3.js"),
  react: () => import("./react.js"),
  lit: () => import("./lit.js"),
  solid: () => import("./solid.js"),
  angularRenaissance: () => import("./angularRenaissance.js"),
  angular: () => import("./angular.js"),
  vue2: () => import("./vue2.js"),
  mithril: () => import("./mithril.js"),
  emberPolaris: () => import("./emberPolaris.js"),
  alpine: () => import("./alpine.js"),
  qwik: () => import("./qwik.js"),
  marko: () => import("./marko.js"),
  svelte5: () => import("./svelte5.js"),
  svelte4: () => import("./svelte4.js"),
  emberOctane: () => import("./emberOctane.js"),
  aurelia2: () => import("./aurelia2.js"),
  aurelia1: () => import("./aurelia1.js"),
};
