// File generated from "node scripts/generateContent.js", DO NOT EDIT/COMMIT
export const sections = [
  {
    sectionId: "reactivity",
    sectionDirName: "1-reactivity",
    title: "Reactivity",
  },
  {
    sectionId: "templating",
    sectionDirName: "2-templating",
    title: "Templating",
  },
  {
    sectionId: "lifecycle",
    sectionDirName: "3-lifecycle",
    title: "Lifecycle",
  },
  {
    sectionId: "component-composition",
    sectionDirName: "4-component-composition",
    title: "Component composition",
  },
  {
    sectionId: "form-input",
    sectionDirName: "6-form-input",
    title: "Form input",
  },
  {
    sectionId: "webapp-features",
    sectionDirName: "7-webapp-features",
    title: "Webapp features",
  },
];
export const snippets = [
  {
    sectionId: "reactivity",
    snippetId: "declare-state",
    snippetDirName: "1-declare-state",
    sectionDirName: "1-reactivity",
    title: "Declare state",
  },
  {
    sectionId: "reactivity",
    snippetId: "update-state",
    snippetDirName: "2-update-state",
    sectionDirName: "1-reactivity",
    title: "Update state",
  },
  {
    sectionId: "reactivity",
    snippetId: "computed-state",
    snippetDirName: "3-computed-state",
    sectionDirName: "1-reactivity",
    title: "Computed state",
  },
  {
    sectionId: "templating",
    snippetId: "minimal-template",
    snippetDirName: "1-minimal-template",
    sectionDirName: "2-templating",
    title: "Minimal template",
  },
  {
    sectionId: "templating",
    snippetId: "styling",
    snippetDirName: "2-styling",
    sectionDirName: "2-templating",
    title: "Styling",
  },
  {
    sectionId: "templating",
    snippetId: "loop",
    snippetDirName: "3-loop",
    sectionDirName: "2-templating",
    title: "Loop",
  },
  {
    sectionId: "templating",
    snippetId: "event-click",
    snippetDirName: "4-event-click",
    sectionDirName: "2-templating",
    title: "Event click",
  },
  {
    sectionId: "templating",
    snippetId: "dom-ref",
    snippetDirName: "5-dom-ref",
    sectionDirName: "2-templating",
    title: "Dom ref",
  },
  {
    sectionId: "templating",
    snippetId: "conditional",
    snippetDirName: "6-conditional",
    sectionDirName: "2-templating",
    title: "Conditional",
  },
  {
    sectionId: "lifecycle",
    snippetId: "on-mount",
    snippetDirName: "1-on-mount",
    sectionDirName: "3-lifecycle",
    title: "On mount",
  },
  {
    sectionId: "lifecycle",
    snippetId: "on-unmount",
    snippetDirName: "2-on-unmount",
    sectionDirName: "3-lifecycle",
    title: "On unmount",
  },
  {
    sectionId: "component-composition",
    snippetId: "props",
    snippetDirName: "1-props",
    sectionDirName: "4-component-composition",
    title: "Props",
  },
  {
    sectionId: "component-composition",
    snippetId: "emit-to-parent",
    snippetDirName: "2-emit-to-parent",
    sectionDirName: "4-component-composition",
    title: "Emit to parent",
  },
  {
    sectionId: "component-composition",
    snippetId: "slot",
    snippetDirName: "3-slot",
    sectionDirName: "4-component-composition",
    title: "Slot",
  },
  {
    sectionId: "component-composition",
    snippetId: "slot-fallback",
    snippetDirName: "4-slot-fallback",
    sectionDirName: "4-component-composition",
    title: "Slot fallback",
  },
  {
    sectionId: "component-composition",
    snippetId: "context",
    snippetDirName: "5-context",
    sectionDirName: "4-component-composition",
    title: "Context",
  },
  {
    sectionId: "form-input",
    snippetId: "input-text",
    snippetDirName: "1-input-text",
    sectionDirName: "6-form-input",
    title: "Input text",
  },
  {
    sectionId: "form-input",
    snippetId: "checkbox",
    snippetDirName: "2-checkbox",
    sectionDirName: "6-form-input",
    title: "Checkbox",
  },
  {
    sectionId: "form-input",
    snippetId: "radio",
    snippetDirName: "3-radio",
    sectionDirName: "6-form-input",
    title: "Radio",
  },
  {
    sectionId: "form-input",
    snippetId: "select",
    snippetDirName: "4-select",
    sectionDirName: "6-form-input",
    title: "Select",
  },
  {
    sectionId: "webapp-features",
    snippetId: "render-app",
    snippetDirName: "1-render-app",
    sectionDirName: "7-webapp-features",
    title: "Render app",
  },
  {
    sectionId: "webapp-features",
    snippetId: "fetch-data",
    snippetDirName: "2-fetch-data",
    sectionDirName: "7-webapp-features",
    title: "Fetch data",
  },
];
